### ISSUE TITLE
Setup.hs fails to compile with ghc-8.2.1 and Cabal-2.0.0.2 

### ISSUE THREAD

**Issue by Arguggi** [nikita-volkov/html-entities#6]
With the new (still unreleased) `Cabal` and the just released `ghc-8.2.1` `Setup.hs` fails to build: 

```
/home/arguggi/projects/html-entities/dist-newstyle/build/x86_64-linux/ghc-8.2.1/html-entities-1.1.4/setup/setup.hs:5:31: error:
    Module
    ‘Distribution.Package’
    does not export
    ‘PackageName(PackageName)’
  |
5 | import Distribution.Package ( PackageName(PackageName), Package, PackageId, InstalledPackageId, packageVersion, packageName )
  |                               ^^^^^^^^^^^^^^^^^^^^^^^^

```
after removing `PackageName` other errors pop up: 
```

/home/arguggi/projects/html-entities/dist-newstyle/build/x86_64-linux/ghc-8.2.1/html-entities-1.1.4/setup/setup.hs:29:40: error:
    • Couldn't match expected type ‘[Char]’
                  with actual type ‘Distribution.Types.UnqualComponentName.UnqualComponentName’
    • In the first argument of ‘(++)’, namely ‘testName suite’
      In the second argument of ‘(++)’, namely ‘testName suite ++ ".hs"’
      In the second argument of ‘(</>)’, namely
        ‘"Build_" ++ testName suite ++ ".hs"’
   |
29 |       rewriteFile (dir </> "Build_" ++ testName suite ++ ".hs") $ unlines
   |                                        ^^^^^^^^^^^^^^

/home/arguggi/projects/html-entities/dist-newstyle/build/x86_64-linux/ghc-8.2.1/html-entities-1.1.4/setup/setup.hs:30:30: error:
    • Couldn't match expected type ‘[Char]’
                  with actual type ‘Distribution.Types.UnqualComponentName.UnqualComponentName’
    • In the first argument of ‘(++)’, namely ‘testName suite’
      In the second argument of ‘(++)’, namely
        ‘testName suite ++ " where"’
      In the expression: "module Build_" ++ testName suite ++ " where"
   |
30 |         [ "module Build_" ++ testName suite ++ " where"
   |                              ^^^^^^^^^^^^^^

/home/arguggi/projects/html-entities/dist-newstyle/build/x86_64-linux/ghc-8.2.1/html-entities-1.1.4/setup/setup.hs:42:18: error:
    • Couldn't match type ‘Distribution.Types.MungedPackageId.MungedPackageId’
                     with ‘Distribution.Types.PackageId.PackageIdentifier’
      Expected type: [(InstalledPackageId, PackageId)]
        Actual type: [(Distribution.Types.UnitId.UnitId,
                       Distribution.Types.MungedPackageId.MungedPackageId)]
    • In the expression:
        nub $ componentPackageDeps xs ++ componentPackageDeps ys
      In an equation for ‘testDeps’:
          testDeps xs ys
            = nub $ componentPackageDeps xs ++ componentPackageDeps ys
   |
42 | testDeps xs ys = nub $ componentPackageDeps xs ++ componentPackageDeps ys
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
```

**Comment by nikita-volkov** [comment]
It's fixed in the latest release now
