### PR TITLE
Fix build with GHC 9.8

### PR DESCRIPTION
**Pull request by tfausak**
I ran into this error:

```
library/HTMLEntities/Prelude.hs:2:5: error: [GHC-69158]
    Conflicting exports for ‘unzip’:
       ‘module Exports’ exports ‘Exports.unzip’
         imported from ‘Data.Functor’ at library/HTMLEntities/Prelude.hs:28:1-30
       ‘module Exports’ exports ‘Exports.unzip’
         imported from ‘Prelude’ at library/HTMLEntities/Prelude.hs:73:1-203
         (and originally defined in ‘GHC.List’)
  |
2 |   ( module Exports,
  |     ^^^^^^^^^^^^^^
```

- https://github.com/haskell/core-libraries-committee/issues/88
- https://github.com/nikita-volkov/bytestring-strict-builder/issues/12

### CODE REVIEW

**Comment by nikita-volkov** [comment]
Oops. Didn't notice that it was a PR and fixed it myself.

Should get released when [the pipeline](https://github.com/nikita-volkov/html-entities/actions/runs/7632211475) finishes.

**Comment by nikita-volkov** [comment]
Thanks!

**Comment by tfausak** [comment]
Thank you! 

For posterity, this was fixed by b1a50b2e6d795d52db22fdeaeac6869a2271a48a and released as [1.1.4.7](https://hackage.haskell.org/package/html-entities-1.1.4.7).
